name: cofi
description: A rofi-like launcher for Sway/Wayland built in Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  riverpod_annotation:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  riverpod_generator:
  custom_lint:
  riverpod_lint:
  flutter_lints:

flutter:
  uses-material-design: true
